### ISSUE TITLE
Wrongly Split for Hindi

### ISSUE THREAD

**Issue by alanwei0** [flmnt/graphemer#6]
I found the result of graphemer and Intl.Segmenter is different for this string below.

source string: `अनुच्छेद`
the result of graphemer: `['अ', 'नु', 'च्', 'छे', 'द']`
the result of Intl.Segmenter: `['अ', 'नु', 'च्छे', 'द']`

**Comment by alanwei0** [comment]
Oh, I found the reason, this project is an implementation on the [Default Grapheme Cluster Boundary](https://unicode.org/reports/tr29/#Default_Grapheme_Cluster_Table), so it doesn't support the tailored grapheme clusters.

**Comment by kiranvj** [comment]
Hi @alanwei0 , I am also facing the same issue for Hindi.  Do you have a fix or any idea how to change the default cluster boundary?

btw: I was using `Intl.Segmenter:` but it doesnt work on Firefox, hence checking `graphemer`

**Comment by alanwei0** [comment]
So sorry @kiranvj, I have no idea about the solution, maybe you could ask the author @mattpauldavies for help.

**Comment by kiranvj** [comment]
@alanwei0  okay, no prob.

@mattpauldavies Is there a way to add a language specific cluster?
